[project]
name = "nyc-duration-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "category-encoders>=2.10.0",
    "ipykernel>=7.3.0",
    "ipython>=9.15.0",
    "jedi>=0.20.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.2",
    "lightgbm>=4.7.0",
    "mlflow>=3.14.0",
    "optuna>=4.9.0",
    "optuna-integration[xgboost]>=4.9.0",
    "protobuf>=4.21.0,<5.0",
    "xgboost>=3.2.0",
]
